project:
  type: website
  output-dir: docs

website:
  title: "Example"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: cv.qmd
        text: CV
      - href: 11-website.qmd
        text: Website
      - href: posts.qmd
        text: Blog

      
format:
  html:
    theme: cosmo
    toc: true
    css: styles.css

editor: visual

