project:
  type: website
  output-dir: docs

website:
  title: "demo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: cv.qmd
        text: CV
      - 11-website.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

