project:
  type: website
  output-dir: docs

website:
  title: "demo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: posts.qmd 
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

